# This file was generated by GoReleaser. DO NOT EDIT.
cask "containerws" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "796c1db16833980152e0485c7c1a4f2cd511503d8ad065f7eb17e0a869712518"
      url "https://github.com/izetmolla/containerws/releases/download/v#{version}/containerws_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4217d7f3d328e2fa068ee1d18b942ef43bafde3107ba8903c09836678e509a65"
      url "https://github.com/izetmolla/containerws/releases/download/v#{version}/containerws_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ca8bb90f1c4bd6c2ccaa2d1dc7c76375f08da2947a06799d075d500e49da70c1"
      url "https://github.com/izetmolla/containerws/releases/download/v#{version}/containerws_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "27dcdca5b9631458a9756639d2690b12142d4b7fe41dd72f048c2485e2ce5b7a"
      url "https://github.com/izetmolla/containerws/releases/download/v#{version}/containerws_#{version}_linux_arm64.tar.gz"
    end
  end

  name "containerws"
  desc "Container Workspace — Linux workspace with web UI, Softwares catalog, and Cloud Shell"
  homepage "https://github.com/izetmolla/containerws"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "containerws"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/containerws"]
    end
    bin = "#{staged_path}/containerws"
    setup_ok = false
    if File.executable?(bin) && File.exist?("/usr/bin/sudo")
      # Passwordless sudo only — otherwise print the manual step.
      result = system_command "/usr/bin/sudo", args: ["-n", bin, "setup"], print_stderr: false, must_succeed: false
      setup_ok = result.success?
    end
    if setup_ok
      ohai "Container Workspace daemon installed (cws --start). UI: http://127.0.0.1:9000"
    else
      ohai "Next step: run 'sudo containerws setup' to create the cws link and start the daemon"
    end
  end

  # No zap stanza required

  caveats <<~EOS
    After install, create the `cws` CLI link and start the background daemon:

      sudo containerws setup

    This installs host dirs, links `cws`, and runs `cws --start` via systemd/launchd/direct.
    Web UI: http://127.0.0.1:9000
  EOS
end
