# This file was generated by GoReleaser. DO NOT EDIT.
cask "containerws" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "918af26c2dc1ad8bf93aa82866eb759d37bc75960f43610b48f036d3b477a6a4"
      url "https://github.com/izetmolla/containerws/releases/download/v#{version}/containerws_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a1e387941185c7448fc6dfe2588bef8c2ddd04f3c63b94e0d5663153600e7121"
      url "https://github.com/izetmolla/containerws/releases/download/v#{version}/containerws_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1777722e2255a3cff4d421e069ad438426f491bbb65d7b78f521fd6a1d3cf69d"
      url "https://github.com/izetmolla/containerws/releases/download/v#{version}/containerws_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4d3425eb0d4f20991187b362c140eb968e6556ed54521b7423d1313598ee0edd"
      url "https://github.com/izetmolla/containerws/releases/download/v#{version}/containerws_#{version}_linux_arm64.tar.gz"
    end
  end

  name "containerws"
  desc "Container Workspace — Linux workspace with web UI, Softwares catalog, and Cloud Shell"
  homepage "https://github.com/izetmolla/containerws"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "containerws"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/containerws"]
    end
    bin = "#{staged_path}/containerws"
    setup_ok = false
    if File.executable?(bin) && File.exist?("/usr/bin/sudo")
      # Passwordless sudo only — otherwise print the manual step.
      result = system_command "/usr/bin/sudo", args: ["-n", bin, "setup"], print_stderr: false, must_succeed: false
      setup_ok = result.success?
    end
    if setup_ok
      ohai "Container Workspace daemon installed (cws --start). UI: http://127.0.0.1:9000"
    else
      ohai "Next step: run 'sudo containerws setup' to create the cws link and start the daemon"
    end
  end

  # No zap stanza required

  caveats <<~EOS
    After install, create the `cws` CLI link and start the background daemon:

      sudo containerws setup

    This installs host dirs, links `cws`, and runs `cws --start` via systemd/launchd/direct.
    Web UI: http://127.0.0.1:9000
  EOS
end
