# This file was generated by GoReleaser. DO NOT EDIT.
cask "containerws" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "ce883105eddcc1d1ff85f6e4f09cf47c57e31d8aefbe0a989aa015b91e84b276"
      url "https://github.com/izetmolla/containerws/releases/download/v#{version}/containerws_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8c7f4642da6d73c4d730046f1b2093aded52e5395ac1c9d68c0986d8a7dd3892"
      url "https://github.com/izetmolla/containerws/releases/download/v#{version}/containerws_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "db4191140bb417ed1cf463de0fee8300cae7b41d6496301f5b4eb19d10660760"
      url "https://github.com/izetmolla/containerws/releases/download/v#{version}/containerws_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "18cb391d4a7bbecc1f130e858f51af584d96162dd877c47d9e80385e3358c6e1"
      url "https://github.com/izetmolla/containerws/releases/download/v#{version}/containerws_#{version}_linux_arm64.tar.gz"
    end
  end

  name "containerws"
  desc "Container Workspace — Linux workspace with web UI, Softwares catalog, and Cloud Shell"
  homepage "https://github.com/izetmolla/containerws"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "containerws"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/containerws"]
    end
    bin = "#{staged_path}/containerws"
    setup_ok = false
    if File.executable?(bin) && File.exist?("/usr/bin/sudo")
      # Passwordless sudo only — otherwise print the manual step.
      result = system_command "/usr/bin/sudo", args: ["-n", bin, "setup"], print_stderr: false, must_succeed: false
      setup_ok = result.success?
    end
    if setup_ok
      ohai "Container Workspace daemon installed (cws --start). UI: http://127.0.0.1:9000"
    else
      ohai "Next step: run 'sudo containerws setup' to create the cws link and start the daemon"
    end
  end

  # No zap stanza required

  caveats <<~EOS
    After install, create the `cws` CLI link and start the background daemon:

      sudo containerws setup

    This installs host dirs, links `cws`, and runs `cws --start` via systemd/launchd/direct.
    Web UI: http://127.0.0.1:9000
  EOS
end
